### ISSUE TITLE
Can you offer training list and more detail of your model

### ISSUE THREAD

**Issue by baoqianyue** [ch10tang/fnm.pytorch#1]
Thanks for you offer this code, I read your code and want to train it，Did you clean the CASIA-WebFace or use all the data in it.
Looking forward to your reply

**Comment by ch10tang** [comment]
You can download the clean version CASIA-WebFace from [face.evoLVe.PyTorch](https://github.com/ZhaoJ9014/face.evoLVe.PyTorch#Data-Zoo).

**Comment by baoqianyue** [comment]
Thanks, are you using the Multi-PIE as the frontal datasets? And can you offer the profile-list and front-list csv file mentioned in the main.py?

**Comment by ch10tang** [comment]
The profile-list and front-list contain the image path from CASIA-WebFace and Multi-PIE, respectively, and all the image paths will combine the path in "-data-place". I'll upload these two documents in the near future.
