### ISSUE TITLE
about the size 

### ISSUE THREAD

**Issue by diaodeyi** [ch10tang/fnm.pytorch#4]

**Comment by diaodeyi** [comment]
why in the code there is transform crop(224) to the profile

**Comment by ch10tang** [comment]
We have to resize/crop the input images to 224x224 for VGGFace2 pre-trained model (i.e., Expert network). The random crop is also a simple way we can apply for data augmentation.

**Comment by diaodeyi** [comment]
thank you , but the GT sent to the diacriminator are also been cropped to 224x224?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ch10tang/fnm.pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月3日(星期四) 下午4:50
收件人:&nbsp;"ch10tang/fnm.pytorch"<fnm.pytorch@noreply.github.com&gt;;
抄送:&nbsp;"拾年。"<1034242067@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ch10tang/fnm.pytorch] about the size  (#4)





 
We have to resize/crop the input images to 224x224 for VGGFace2 pre-trained model (i.e., Expert network). The random crop is also a simple way we can apply for data augmentation.

**Comment by ch10tang** [comment]
Yes, that's right.

**Comment by diaodeyi** [comment]
thanks，if you don't mand, could you tell me where are the documents in run folder comes from?&nbsp; i don't figure out in the code.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ch10tang/fnm.pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 上午8:08
收件人:&nbsp;"ch10tang/fnm.pytorch"<fnm.pytorch@noreply.github.com&gt;;
抄送:&nbsp;"拾年。"<1034242067@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ch10tang/fnm.pytorch] about the size  (#4)





 
Yes, that's right.

**Comment by diaodeyi** [comment]
Excuse me，Does this model can't been trained with muti-GPU？&nbsp;




- -----------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ch10tang/fnm.pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 上午8:08
收件人:&nbsp;"ch10tang/fnm.pytorch"<fnm.pytorch@noreply.github.com&gt;;
抄送:&nbsp;"拾年。"<1034242067@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ch10tang/fnm.pytorch] about the size  (#4)





 
Yes, that's right.

**Comment by ch10tang** [comment]
Please run "main.py" scripts with the python command.

Data parallelism has not implemented in the code yet.

**Comment by diaodeyi** [comment]
Thank you! by the way , where is the evaluation code?
