### ISSUE TITLE
about the generation inference

### ISSUE THREAD

**Issue by diaodeyi** [ch10tang/fnm.pytorch#5]
Missing key(s) in state_dict: "module.fc.filter.weight", "module.fc.filter.bias", "module.fc2.bias". 
        Unexpected key(s) in state_dict: "module.fc.weight", "module.fc.bias". 
        size mismatch for module.fc2.weight: copying a param with shape torch.Size([80013, 256]) from checkpoint, the shape in current model is torch.Size([79077, 256]).

 I have try many checkpoints， It seems your model doesn't support the checkpoint loading in the generation？

**Comment by diaodeyi** [comment]
？ Is there someone else?

**Comment by ch10tang** [comment]
Sorry for the late response.
It seems that you used the incorrect LightCNN model. The output sizes of  "network_29layers" and "network_29layers_v2" are  receptively 79077 and 80013. In the default setting of the test code, I used "network_29layers" model. 

You can send me the e-mail d10803002@mail.ntust.edu.tw if you have any other questions.
